name: wattsense
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  equatable: ^2.0.7
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
